### ISSUE TITLE
Update LibGit2Sharp

### ISSUE THREAD

**Issue by reactormonk** [tboby/cwtools-vscode#33]
I'm getting the error described in this issue here https://github.com/GitTools/GitVersion/issues/1852 - I also linked directly to the fix. Would help getting it to run on Linux.

**Comment by tboby** [comment]
@reactormonk I don't think I can easily get hold of a system to reproduce, would you mind testing this version?

https://we.tl/t-iYsZzNwUyy

To manually install:
1. Download file
2. Open VS Code
3. Go to extensions
4. In three dots menu "Install from VSIX..."
5. Wait for it to finish/ask to reload

When I next release a version of cwtools-vscode it should auto-update you back to the normal release track.

**Comment by reactormonk** [comment]
I'm sorry, I deleted too many notifications at once :-( The file isn't available anymore.

**Comment by MarkSill** [comment]
I also get this issue. It works on Windows 10 but causes this with Ubuntu 20.10. The error:

```
[Error - 12:35:52 AM] cwtools git error, recovering, error: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'git2-106a5f2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-106a5f2: cannot open shared object file: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_repository_open_ext(git_repository*& repository, FilePath path, RepositoryOpenFlags flags, FilePath ceilingDirs)
   at LibGit2Sharp.Core.Proxy.git_repository_open_ext(String path, RepositoryOpenFlags flags, String ceilingDirs)
   at LibGit2Sharp.Repository.IsValid(String path)
   at Main.Git.initOrUpdateRules(String repoPath, String gameCacheDir, Boolean stable, Boolean first) in C:\Users\Thomas\Git\cwtools-vscode\src\Main\Git.fs:line 12
```

As a temporary workaround, you can follow the directions on the [cwtools-stellaris-config](https://github.com/cwtools/cwtools-stellaris-config#cwtools-config-rules-for-stellaris) repo.
